var teams = [
  {
      name: 'Metro City',
      league: 'South',
      gamesPlayed: 0,
      points: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      wins: 0,
      draws: 0,
      losses: 0,
      offence: 79,
      defence: 78,
      agression: 50,
      luck: 50,
      played: 'Metro City',
},
{
      name: 'St Marry',
      league: 'South',
      gamesPlayed: 0,
      points: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      wins: 0,
      draws: 0,
      losses: 0,
      offence: 79,
      defence: 78,
      agression: 50,
      luck: 50,
      played: 'St Marry',
},
{
    name: 'Tripper City',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Tripper City',
},
{
    name: 'Port Hilo',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Port Hilo',
},
{
    name: 'Outside City',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Outside City',
},
{
    name: 'Green Bay',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Green Bay',
},
{
    name: 'Metro Bay',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Metro Bay',
},
{
    name: 'South Central Metro',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'South Central Metro',
},
{
    name: 'Orlean City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Orlean City',
},
{
    name: 'Santos',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Santos',
},
{
    name: 'Atlan',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Atlan',
},
{
    name: 'Swirl City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Swirl City',
},
{
    name: 'Mega City 1',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Mega City 1',
},
{
    name: 'Mega City 2',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Mega City 2',
},
{
    name: 'Omacia',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Omacia',
},
{
    name: 'Virgin City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Virgin City',
},
]
