var teams = [
  {
      name: 'Metro City',
      league: 'South',
      gamesPlayed: 0,
      points: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      wins: 0,
      draws: 0,
      losses: 0,
      offence: 79,
      defence: 78,
      agression: 50,
      luck: 50,
      played: 'Metro City',
},
{
      name: 'St Marry',
      league: 'South',
      gamesPlayed: 0,
      points: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      wins: 0,
      draws: 0,
      losses: 0,
      offence: 79,
      defence: 78,
      agression: 50,
      luck: 50,
      played: 'St Marry',
},
{
    name: 'Tripper City',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Tripper City',
},
{
    name: 'Port Hilo',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Port Hilo',
},
{
    name: 'Outside City',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Outside City',
},
{
    name: 'Green Bay',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Green Bay',
},
{
    name: 'Metro Bay',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Metro Bay',
},
{
    name: 'South Central Metro',
    league: 'South',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'South Central Metro',
},
{
    name: 'Orlean City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Orlean City',
},
{
    name: 'Santos',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Santos',
},
{
    name: 'Atlan',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Atlan',
},
{
    name: 'Swirl City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Swirl City',
},
{
    name: 'Mega City 1',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Mega City 1',
},
{
    name: 'Mega City 2',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Mega City 2',
},
{
    name: 'Omacia',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Omacia',
},
{
    name: 'Virgin City',
    league: 'North',
    gamesPlayed: 0,
    points: 0,
    goalsFor: 0,
    goalsAgainst: 0,
    wins: 0,
    draws: 0,
    losses: 0,
    offence: 79,
    defence: 78,
    agression: 50,
    luck: 50,
    played: 'Virgin City',
},
]

var fixtures =  [
{
  league: 'North',
  week: 1,
  game1: 'Orlean City vs Santos',
  game2: 'Virgin City vs Omacia',
  game3: 'Mega City 2 vs Swirl City',
  game4: 'Atlan City vs Mega City 2',
},
{
  league: 'North',
  week: 2,
  game1: 'Orlean City vs Omacia',
  game2: 'Santos vs Swirl',
  game3: 'Virgin City vs Mega City 1',
  game4: 'Mega City 2 vs Atlan City',
},
{
  league: 'North',
  week: 3,
  game1: 'Orlean City vs Swirl City',
  game2: 'Omacia vs Mega City 1',
  game3: 'Santos vs Atlan City',
  game4: 'Virgin City vs Mega City 2',
},
{
  league: 'North',
  week: 4,
  game1: 'Orlean City',
  game2: 'Swirl City vs Atlan City',
  game3: 'Omacia vs Mega City 2',
  game4: 'Santos vs Virgin City',
},
{
  leauge: 'North',
  week: 5,
  game1: 'Orlean City vs Atlan City',
  game2: 'Mega City 2 vs Mega City 2',
  game3: 'Swirl City vs Virgin city',
  game4: 'Omacia vs Santos',
},
{
  league: 'North',
  week: 6,
  game1: 'Orlean City vs Mega City 1',
  game2: 'Atlan City vs Virgin City 2',
  game3: 'Mega City 1 vs Santos',
  game4: 'Swirl City vs Omacia',
},
{
  league: 'North',
  week: 7,
  game1: 'Orlean City vs Virgin City',
  game2: 'Mega city 2 vs Santos',
  game3: 'Atlan City vs Omacia',
  game4: 'Mega City 1 vs Swirl City',
},

]
